### PR TITLE
Added IHornHarvestable support for all crops.

### PR DESCRIPTION
**Pull request by Penrif**
Loads of copypasta, it would be handy if the Inferium crops inherited from BlockMysticalCrop.

### CODE REVIEW

**Comment by BlakeBr0** [comment]
I can't get this to work in my dev environment because botania wants baubles to be installed and baubles causes classnotfound errors.

**Comment by Penrif** [comment]
What version of Baubles are you using?  I tested against Baubles-1.10.2-1.3.9.jar from https://mods.curse.com/mc-mods/minecraft/227083-baubles#t1:other-downloads

**Comment by BlakeBr0** [comment]
Yea I used that one as well. For some reason I don't think any mods work in my dev env, which is unfortunate.
I'll try to get it fixed soon.

**Comment by BlakeBr0** [comment]
Alright, got it working. I'll be adding this into the next update.

**Pull request closed without merging**
